# Path: /path/to/iso/build/airootfs/etc/mkinitcpio.conf
MODULES=(r8169)
BINARIES=()
FILES=()
HOOKS=(base udev microcode modconf memdisk archiso block filesystems keyboard)
COMPRESSION="xz"
COMPRESSION_OPTIONS=(-9e)
