# Calamares users module
---
defaultGroups:
  - name: users
    must_exist: true
    system: false
  - name: video
    must_exist: true
    system: true
  - name: audio
    must_exist: true
    system: true
  - name: optical
    must_exist: true
    system: true
  - name: storage
    must_exist: true
    system: true
  - name: lp
    must_exist: true
    system: true
  - name: wheel
    must_exist: true
    system: true
  - name: input
    must_exist: true
    system: true
  - name: sys
    must_exist: true
    system: true

autologinGroup: autologin
doAutologin: false

sudoersGroup: wheel
setRootPassword: true
doReusePassword: false

userShell: /bin/bash

avatarFilePath: ~/.face
